apiVersion: apps/v1
kind: Deployment
metadata:
  name: roar-web
  labels:
    name: roar-web
    app: roar-web
  namespace: default
spec:
  selector:
    matchLabels:
      app: roar-web  
  replicas: 5
  template:
    metadata:
      labels:
        name: roar-web
        app: roar-web
    spec:
      containers:
      - name: roar-web
        image: 172.20.7.100:5000/bclaster/roar-web:1.0.1
        ports:
        - name: web
          containerPort: 8080
